### ISSUE TITLE
Roadmap for The Gurkan Programming Language for the year 2021

### ISSUE THREAD

**Issue by uncomfyhalomacro** [gurkult/meta#3]
Repo: [The Gurkan Programming Language](https://github.com/gurkult/gurklang)
What was discussed: [Bike Shed](https://github.com/gurkult/gurklang/discussions/2)

This issue is to tackle **the need of a roadmap** for the Gurkan Programming Language . For now, this will be an incomplete issue until we finished the following tasks:
- [x] Finalized the syntax of the language
- [x] Finalized what language to use to build the Gurkan Programming Language
- [x] Finalized the lexers and parsers
- [ ] Standard Libraries and Imports
- [x] Preliminary Documentation

Each task should be fully documented, preferably as a markdown file, including sample code blocks, what paradigm was used, and the idea behind the language and whatever that could be documented because it is relevant for the Gurkan Programming Language. Feel free to comment, rebut, refuse, hate, or give suggestions for this issue.

Updated as of **December 31, 2020**
